# Generated by Django 5.0.1 on 2024-01-22 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adnd_class', models.CharField(max_length=25)),
                ('race', models.CharField(max_length=20)),
                ('alignment', models.CharField(choices=[('CG', 'Chaotic Good'), ('NG', 'Neutral Good'), ('LG', 'Lawful Good'), ('CN', 'Chaotic Neutral'), ('TN', 'True Neutral'), ('LN', 'Lawful Neutral'), ('CE', 'Chaotic Evil'), ('NE', 'Neutral Evil'), ('LE', 'Lawful Evil'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('str', models.IntegerField()),
                ('str_percentile', models.IntegerField(null=True)),
                ('dex', models.IntegerField()),
                ('con', models.IntegerField()),
                ('int', models.IntegerField()),
                ('wis', models.IntegerField()),
                ('cha', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.game')),
            ],
        ),
    ]
