# Generated by Django 5.0.1 on 2024-01-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='str_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('OR', 'Original'), ('MO', 'Mod'), ('FA', 'Fanart'), ('BE', 'Beamdog')], default='FA', max_length=2)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('npc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.npc')),
            ],
        ),
    ]
