# Generated by Django 5.0.1 on 2024-01-23 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_npc_str_percentile_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 23, 13, 41, 15, 492491, tzinfo=datetime.timezone.utc)),
        ),
    ]
