# Generated by Django 5.0.1 on 2024-01-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_portrait_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='game',
        ),
        migrations.CreateModel(
            name='NpcInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('OR', 'Original'), ('MO', 'Mod'), ('FA', 'Fanart'), ('BE', 'Beamdog')], default='MO', max_length=2)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.game')),
                ('npc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.npc')),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='game',
            field=models.ManyToManyField(through='gallery.NpcInGame', to='gallery.game'),
        ),
    ]
