# Generated by Django 5.0.1 on 2024-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_npc_game_npcingame_npc_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='web_image',
            field=models.ImageField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
    ]
