# Generated by Django 5.0.1 on 2024-01-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_portrait_web_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portrait',
            name='web_image',
            field=models.ImageField(upload_to='web_portraits'),
        ),
    ]
