# Generated by Django 5.0.1 on 2024-01-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_portrait_web_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='zip_files',
            field=models.FileField(default='default.zip', upload_to='zip_files'),
            preserve_default=False,
        ),
    ]
