# Generated by Django 5.0.1 on 2024-01-23 21:10

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_portrait_zip_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portrait',
            name='web_image',
            field=models.ImageField(upload_to=gallery.models.web_image_with_hash),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='zip_files',
            field=models.FileField(upload_to=gallery.models.zip_file_with_hash),
        ),
    ]
