# Generated by Django 5.0.1 on 2024-01-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_portrait_web_image_alter_portrait_zip_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portrait',
            old_name='zip_files',
            new_name='zip_file',
        ),
    ]
