# Generated by Django 5.0.1 on 2024-01-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_rename_zip_files_portrait_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcingame',
            name='origin',
            field=models.CharField(choices=[('OR', 'Original'), ('MO', 'Mod'), ('BE', 'Beamdog')], default='OR', max_length=2),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='origin',
            field=models.CharField(choices=[('OR', 'Original'), ('MO', 'Mod'), ('BE', 'Beamdog')], default='OR', max_length=2),
        ),
    ]
