# Generated by Django 5.0.1 on 2024-01-26 00:26

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_npcingame_origin_alter_portrait_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(choices=[('OR', 'Original'), ('MO', 'Mod'), ('BE', 'Beamdog')], default='OR', max_length=2)),
                ('img_170', models.ImageField(upload_to=gallery.models.char_portrait_with_hash)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
