# Generated by Django 5.0.1 on 2024-01-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_alter_portrait_npc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portrait',
            old_name='npc',
            new_name='character',
        ),
    ]
