# Generated by Django 5.0.1 on 2024-01-26 01:33

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_rename_npc_portrait_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='web_image',
            field=models.ImageField(null=True, upload_to=gallery.models.web_image_with_hash),
        ),
    ]
