# Generated by Django 5.0.1 on 2024-01-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_npc_web_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_name',
            field=models.CharField(default='temp', max_length=10),
            preserve_default=False,
        ),
    ]
