# Generated by Django 5.0.1 on 2024-01-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_game_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.SmallIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
