# Generated by Django 5.0.1 on 2024-01-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_alter_game_options_game_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='codename',
            new_name='slug',
        ),
    ]
