# Generated by Django 5.0.1 on 2024-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_rename_codename_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title_screen_320',
            field=models.ImageField(null=True, upload_to='games'),
        ),
    ]
