# Generated by Django 5.0.1 on 2024-01-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_game_title_screen_320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title_screen_320',
            new_name='title_screen',
        ),
    ]
