# Generated by Django 5.0.1 on 2024-01-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_game_developer_game_release_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='portrait',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='npc',
            name='admin_note',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
