# Generated by Django 5.0.1 on 2024-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_alter_character_options_alter_npc_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='origin',
            field=models.CharField(choices=[('OR', 'Original'), ('MO', 'Mod'), ('BE', 'Beamdog'), ('FA', 'Fanart')], default='OR', max_length=2),
        ),
    ]
