# Generated by Django 5.0.1 on 2024-01-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_alter_npc_description_alter_portrait_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(default='emptyslug'),
            preserve_default=False,
        ),
    ]
