# Generated by Django 5.0.1 on 2024-01-31 16:11

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0026_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('description',)},
        ),
        migrations.AlterField(
            model_name='portrait',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to=gallery.models.zip_file_with_hash),
        ),
    ]
