# Generated by Django 5.0.1 on 2024-02-02 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0028_alter_portrait_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('in_use', models.BooleanField(default=True)),
                ('max_uses', models.PositiveSmallIntegerField(default=20)),
                ('times_used', models.PositiveSmallIntegerField(default=0)),
                ('added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('added',),
            },
        ),
    ]
