# Generated by Django 5.0.1 on 2024-02-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0030_party_pc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='party',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='gallery.npc'),
        ),
    ]
