# Generated by Django 5.0.1 on 2024-02-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gallery', '0032_alter_pc_adnd_class_alter_pc_alignment_alter_pc_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.party')),
            ],
            options={
                'ordering': ('position',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gallery_slo_content_ceb3da_idx')],
            },
        ),
    ]
