# Generated by Django 5.0.1 on 2024-02-05 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0034_alter_slot_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
