# Generated by Django 5.0.1 on 2024-02-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0038_alter_npc_cha_alter_npc_con_alter_npc_dex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
